source 'https://rubygems.org'
ruby '2.1.2'

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

gem 'httparty'

group :test do
  gem 'shoulda-matchers'
  gem 'rack-test'
  gem 'rspec'
  gem 'capybara'
  gem 'jasmine'
end

group :test, :development do
  gem 'factory_girl'
  gem 'faker'
end
