source 'https://rubygems.org'

# PostgreSQL driver
gem 'sqlite3'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activesupport'
gem 'activerecord'
gem 'bcrypt'

gem 'rake'

gem 'shotgun'

group :test do
  gem 'database_cleaner', '~> 1.4.1'
  gem 'shoulda-matchers'
  gem 'rack-test'
  gem 'rspec'
  gem 'capybara'
end

group :test, :development do
  gem 'factory_girl'
  gem 'faker'
end
